name: lint

on: [push, pull_request]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run:|
          python -m venv venv
          . venv/bin/activate
          ./scripts/install.sh

      - name: Run lint script
        run: ./scripts/lint.sh

      - name: Run unit test
        run: pytest tests
